// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package ntpdb

import (
	"context"
)

type Querier interface {
	GetServerNetspeed(ctx context.Context, ip string) (uint32, error)
	GetZoneStatsData(ctx context.Context) ([]GetZoneStatsDataRow, error)
	GetZoneStatsV2(ctx context.Context, ip string) ([]GetZoneStatsV2Row, error)
}

var _ Querier = (*Queries)(nil)
